package message

type Message interface {
	Topic() string
	Bytes() ([]byte, error)
}

// Source is implemented by types that can generate a Message stream.
type Source interface {
	// Output returns a channel of Messages provided by a Source. When the
	// Source has no more Messages to send, it should close the channel.
	Output() <-chan Message
}

// SourceError is implemented by Sources that can respond to error values
// generated by their clients while processing a Message.
type SourceError interface {
	Source
	// Err returns a channel on which clients can send values. Clients
	// should close the channel when they have nothing more to send.
	Err() chan<- error
}
