package schema

import (
	"encoding/json"
	"time"

	"github.com/ESG-USA/Auklet-Client-C/broker"
)

// profile represents profile data as expected by broker consumers.
type profile struct {
	metadata
	// Time is the Unix epoch time (in milliseconds) at which a tree was
	// received.
	Time int64 `json:"timestamp"`
	// Tree represents the profile tree data generated by an agent.
	Tree node `json:"tree"`
}

type node struct {
	Fn       int64  `json:"functionAddress"`
	Cs       int64  `json:"callSiteAddress,omitempty"`
	Ncalls   int    `json:"nCalls,omitempty"`
	Nsamples int    `json:"nSamples,omitempty"`
	Callees  []node `json:"callees,omitempty"`
}

func nowMilli() int64 {
	return time.Now().UnixNano() / 1000000 // milliseconds
}

// NewProfile creates a Profile for app out of raw message data.
func NewProfile(data []byte, app App) broker.Message {
	var p profile
	err := json.Unmarshal(data, &p)
	if err != nil {
		p.Error = err.Error()
	}
	p.metadata = newMetadata(app)
	p.Time = nowMilli()
	return marshal(p, broker.Profile)
}
