// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema/schema.proto

package schema // import "github.com/ESG-USA/Auklet-Client-C/schema"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import device "github.com/ESG-USA/Auklet-Client-C/device"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Exit struct {
	Application          string          `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Checksum             string          `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	PublicIP             string          `protobuf:"bytes,3,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	Id                   string          `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string          `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExitStatus           int32           `protobuf:"varint,6,opt,name=exitStatus,proto3" json:"exitStatus,omitempty"`
	Signal               string          `protobuf:"bytes,7,opt,name=signal,proto3" json:"signal,omitempty"`
	StackTrace           []*StackTrace   `protobuf:"bytes,8,rep,name=stackTrace,proto3" json:"stackTrace,omitempty"`
	MacAddressHash       string          `protobuf:"bytes,9,opt,name=macAddressHash,proto3" json:"macAddressHash,omitempty"`
	SystemMetrics        *device.Metrics `protobuf:"bytes,10,opt,name=systemMetrics,proto3" json:"systemMetrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Exit) Reset()         { *m = Exit{} }
func (m *Exit) String() string { return proto.CompactTextString(m) }
func (*Exit) ProtoMessage()    {}
func (*Exit) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_d75e329f48f13a96, []int{0}
}
func (m *Exit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exit.Unmarshal(m, b)
}
func (m *Exit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exit.Marshal(b, m, deterministic)
}
func (dst *Exit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exit.Merge(dst, src)
}
func (m *Exit) XXX_Size() int {
	return xxx_messageInfo_Exit.Size(m)
}
func (m *Exit) XXX_DiscardUnknown() {
	xxx_messageInfo_Exit.DiscardUnknown(m)
}

var xxx_messageInfo_Exit proto.InternalMessageInfo

func (m *Exit) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Exit) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *Exit) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *Exit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Exit) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Exit) GetExitStatus() int32 {
	if m != nil {
		return m.ExitStatus
	}
	return 0
}

func (m *Exit) GetSignal() string {
	if m != nil {
		return m.Signal
	}
	return ""
}

func (m *Exit) GetStackTrace() []*StackTrace {
	if m != nil {
		return m.StackTrace
	}
	return nil
}

func (m *Exit) GetMacAddressHash() string {
	if m != nil {
		return m.MacAddressHash
	}
	return ""
}

func (m *Exit) GetSystemMetrics() *device.Metrics {
	if m != nil {
		return m.SystemMetrics
	}
	return nil
}

type StackTrace struct {
	FunctionAddress      uint64   `protobuf:"varint,1,opt,name=functionAddress,proto3" json:"functionAddress,omitempty"`
	CallSiteAddress      uint64   `protobuf:"varint,2,opt,name=callSiteAddress,proto3" json:"callSiteAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackTrace) Reset()         { *m = StackTrace{} }
func (m *StackTrace) String() string { return proto.CompactTextString(m) }
func (*StackTrace) ProtoMessage()    {}
func (*StackTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_d75e329f48f13a96, []int{1}
}
func (m *StackTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackTrace.Unmarshal(m, b)
}
func (m *StackTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackTrace.Marshal(b, m, deterministic)
}
func (dst *StackTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackTrace.Merge(dst, src)
}
func (m *StackTrace) XXX_Size() int {
	return xxx_messageInfo_StackTrace.Size(m)
}
func (m *StackTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_StackTrace.DiscardUnknown(m)
}

var xxx_messageInfo_StackTrace proto.InternalMessageInfo

func (m *StackTrace) GetFunctionAddress() uint64 {
	if m != nil {
		return m.FunctionAddress
	}
	return 0
}

func (m *StackTrace) GetCallSiteAddress() uint64 {
	if m != nil {
		return m.CallSiteAddress
	}
	return 0
}

type Profile struct {
	Application          string   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Checksum             string   `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	PublicIP             string   `protobuf:"bytes,3,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tree                 *Tree    `protobuf:"bytes,6,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_d75e329f48f13a96, []int{2}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Profile) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *Profile) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Profile) GetTree() *Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type Tree struct {
	FunctionAddress      uint64   `protobuf:"varint,1,opt,name=functionAddress,proto3" json:"functionAddress,omitempty"`
	CallSiteAddress      uint64   `protobuf:"varint,2,opt,name=callSiteAddress,proto3" json:"callSiteAddress,omitempty"`
	NCalls               uint32   `protobuf:"varint,3,opt,name=nCalls,proto3" json:"nCalls,omitempty"`
	NSamples             uint32   `protobuf:"varint,4,opt,name=nSamples,proto3" json:"nSamples,omitempty"`
	Callees              []*Tree  `protobuf:"bytes,5,rep,name=callees,proto3" json:"callees,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_d75e329f48f13a96, []int{3}
}
func (m *Tree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tree.Unmarshal(m, b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
}
func (dst *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(dst, src)
}
func (m *Tree) XXX_Size() int {
	return xxx_messageInfo_Tree.Size(m)
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

func (m *Tree) GetFunctionAddress() uint64 {
	if m != nil {
		return m.FunctionAddress
	}
	return 0
}

func (m *Tree) GetCallSiteAddress() uint64 {
	if m != nil {
		return m.CallSiteAddress
	}
	return 0
}

func (m *Tree) GetNCalls() uint32 {
	if m != nil {
		return m.NCalls
	}
	return 0
}

func (m *Tree) GetNSamples() uint32 {
	if m != nil {
		return m.NSamples
	}
	return 0
}

func (m *Tree) GetCallees() []*Tree {
	if m != nil {
		return m.Callees
	}
	return nil
}

type AppLog struct {
	Application          string          `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Checksum             string          `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	PublicIP             string          `protobuf:"bytes,3,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	Id                   string          `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string          `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              []byte          `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	MacAddressHash       string          `protobuf:"bytes,7,opt,name=macAddressHash,proto3" json:"macAddressHash,omitempty"`
	SystemMetrics        *device.Metrics `protobuf:"bytes,8,opt,name=systemMetrics,proto3" json:"systemMetrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AppLog) Reset()         { *m = AppLog{} }
func (m *AppLog) String() string { return proto.CompactTextString(m) }
func (*AppLog) ProtoMessage()    {}
func (*AppLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_d75e329f48f13a96, []int{4}
}
func (m *AppLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLog.Unmarshal(m, b)
}
func (m *AppLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLog.Marshal(b, m, deterministic)
}
func (dst *AppLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLog.Merge(dst, src)
}
func (m *AppLog) XXX_Size() int {
	return xxx_messageInfo_AppLog.Size(m)
}
func (m *AppLog) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLog.DiscardUnknown(m)
}

var xxx_messageInfo_AppLog proto.InternalMessageInfo

func (m *AppLog) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *AppLog) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *AppLog) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *AppLog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppLog) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *AppLog) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *AppLog) GetMacAddressHash() string {
	if m != nil {
		return m.MacAddressHash
	}
	return ""
}

func (m *AppLog) GetSystemMetrics() *device.Metrics {
	if m != nil {
		return m.SystemMetrics
	}
	return nil
}

func init() {
	proto.RegisterType((*Exit)(nil), "schema.Exit")
	proto.RegisterType((*StackTrace)(nil), "schema.StackTrace")
	proto.RegisterType((*Profile)(nil), "schema.Profile")
	proto.RegisterType((*Tree)(nil), "schema.Tree")
	proto.RegisterType((*AppLog)(nil), "schema.AppLog")
}

func init() { proto.RegisterFile("schema/schema.proto", fileDescriptor_schema_d75e329f48f13a96) }

var fileDescriptor_schema_d75e329f48f13a96 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0xc5, 0x4e, 0x62, 0x27, 0x37, 0x4d, 0x0b, 0x2a, 0x0c, 0x51, 0xc6, 0x30, 0x7e, 0x28, 0x1e,
	0x23, 0x09, 0x64, 0xec, 0x03, 0xb2, 0x50, 0xb6, 0xc1, 0x06, 0xc5, 0xee, 0x5e, 0xf6, 0x34, 0x45,
	0xbe, 0x4d, 0x44, 0x24, 0xdb, 0x58, 0xf2, 0xe8, 0x3e, 0x61, 0xdf, 0x33, 0xd8, 0xbf, 0xec, 0x6f,
	0x86, 0x65, 0x3b, 0x4d, 0xc3, 0x1e, 0xfa, 0x32, 0xd6, 0x27, 0x71, 0xce, 0xb9, 0xbe, 0xf6, 0x3d,
	0xf7, 0x58, 0x70, 0xae, 0xf9, 0x16, 0x15, 0x9b, 0x37, 0xc7, 0xac, 0x28, 0x73, 0x93, 0x13, 0xaf,
	0x41, 0x17, 0xe7, 0x29, 0x7e, 0x13, 0x1c, 0xe7, 0xcd, 0xd1, 0x88, 0xe1, 0x6f, 0x17, 0xfa, 0x57,
	0x77, 0xc2, 0x90, 0x00, 0xc6, 0xac, 0x28, 0xa4, 0xe0, 0xcc, 0x88, 0x3c, 0xa3, 0x4e, 0xe0, 0x44,
	0xa3, 0xf8, 0x90, 0x22, 0x17, 0x30, 0xe4, 0x5b, 0xe4, 0x3b, 0x5d, 0x29, 0xea, 0x5a, 0x79, 0x8f,
	0x6b, 0xad, 0xa8, 0xd6, 0x52, 0xf0, 0x0f, 0xd7, 0xb4, 0xd7, 0x68, 0x1d, 0x26, 0xa7, 0xe0, 0x8a,
	0x94, 0xf6, 0x2d, 0xeb, 0x8a, 0x94, 0x3c, 0x87, 0x91, 0x11, 0x0a, 0xb5, 0x61, 0xaa, 0xa0, 0x03,
	0x4b, 0xdf, 0x13, 0xe4, 0x05, 0x00, 0xde, 0x09, 0x93, 0x18, 0x66, 0x2a, 0x4d, 0xbd, 0xc0, 0x89,
	0x06, 0xf1, 0x01, 0x43, 0x9e, 0x81, 0xa7, 0xc5, 0x26, 0x63, 0x92, 0xfa, 0xf6, 0xd1, 0x16, 0x91,
	0x05, 0x80, 0x36, 0x8c, 0xef, 0x6e, 0x4a, 0xc6, 0x91, 0x0e, 0x83, 0x5e, 0x34, 0x5e, 0x90, 0x59,
	0x6b, 0x44, 0xb2, 0x57, 0xe2, 0x83, 0x2a, 0x72, 0x09, 0xa7, 0x8a, 0xf1, 0x65, 0x9a, 0x96, 0xa8,
	0xf5, 0x7b, 0xa6, 0xb7, 0x74, 0x64, 0x7b, 0x1e, 0xb1, 0xe4, 0x0d, 0x4c, 0xf4, 0x77, 0x6d, 0x50,
	0x7d, 0x42, 0x53, 0x0a, 0xae, 0x29, 0x04, 0x4e, 0x34, 0x5e, 0x9c, 0xcd, 0x5a, 0x2b, 0x5b, 0x3a,
	0x7e, 0x58, 0x15, 0x7e, 0x05, 0xb8, 0x7f, 0x31, 0x89, 0xe0, 0xec, 0xb6, 0xca, 0x78, 0x6d, 0x65,
	0xdb, 0xdb, 0x9a, 0xdc, 0x8f, 0x8f, 0xe9, 0xba, 0x92, 0x33, 0x29, 0x13, 0x61, 0xb0, 0xab, 0x74,
	0x9b, 0xca, 0x23, 0x3a, 0xfc, 0xe9, 0x80, 0x7f, 0x5d, 0xe6, 0xb7, 0x42, 0xe2, 0xff, 0x5c, 0x60,
	0xef, 0x70, 0x81, 0x01, 0xf4, 0x4d, 0x89, 0x68, 0x57, 0x37, 0x5e, 0x9c, 0x74, 0x2b, 0xb8, 0x29,
	0x11, 0x63, 0xab, 0x84, 0xbf, 0x1c, 0xe8, 0xd7, 0xf0, 0x5f, 0x58, 0x52, 0xe7, 0x23, 0x5b, 0x31,
	0x29, 0xb5, 0x1d, 0x63, 0x12, 0xb7, 0xa8, 0x1e, 0x30, 0x4b, 0x98, 0x2a, 0x24, 0x6a, 0x3b, 0xca,
	0x24, 0xde, 0x63, 0x72, 0x09, 0x7e, 0xdd, 0x06, 0x51, 0xd3, 0x81, 0x0d, 0xce, 0xc3, 0xaf, 0xee,
	0xc4, 0xf0, 0x87, 0x0b, 0xde, 0xb2, 0x28, 0x3e, 0xe6, 0x9b, 0x27, 0xf3, 0xbb, 0x50, 0xf0, 0x15,
	0x6a, 0xcd, 0x36, 0x8d, 0xe1, 0x27, 0x71, 0x07, 0xff, 0x12, 0x6e, 0xff, 0x71, 0xe1, 0x1e, 0x3e,
	0x26, 0xdc, 0x6f, 0x5f, 0x7d, 0x79, 0xb9, 0x11, 0x66, 0x5b, 0xad, 0x67, 0x3c, 0x57, 0xf3, 0xab,
	0xe4, 0xdd, 0xf4, 0x73, 0xb2, 0x9c, 0x2f, 0xab, 0x9d, 0x44, 0x33, 0x5d, 0x49, 0x81, 0x99, 0x99,
	0xae, 0xda, 0x8b, 0x68, 0xed, 0xd9, 0xcb, 0xe6, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf,
	0x4a, 0xba, 0x3f, 0xa0, 0x04, 0x00, 0x00,
}
