package kafka

// This file defines interfaces for manipulating streams of Kafka
// messages.

type Topic int

const (
	ProfileTopic Topic = iota
	EventTopic
	LogTopic
)

// Message is implemented by types that can be sent as Kafka messages.
type Message interface {
	Topic() Topic
	Bytes() []byte
}

// MessageSource is implemented by types that can generate a Message stream.
type MessageSource interface {
	// Output returns a channel of Messages provided by a Source. A source
	// indicates when it has no more Messages to send by closing the
	// channel.
	Output() <-chan Message
}

// MessageSourceError is implemented by Sources that can respond to error
// values generated by their clients while processing a Message.
type MessageSourceError interface {
	MessageSource
	// Err returns a channel on which clients can send values. Clients
	// close the channel to indicate that they have nothing more to send.
	Err() chan<- error
}
